---
name: 'EBBR CI Build'

# yamllint disable-line rule:truthy
on:
  push:
    branches: '**'
    tags: 'v*'

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Compute IRC message'
        # We compute a message only in the following cases:
        # - Push to the main branch
        # - Pull request opened
        run: |
          case "${{ github.event_name }}" in
          push)
            case "${{ github.event.ref }}" in
            refs/heads/main|refs/tags/*)
              cat >message <<EOF
          ${{ github.event.head_commit.message }}
          EOF
              title=$(head -1 message)
              msg="Push ${{ github.event.ref }} (\"$title\")"
              url="${{ github.event.head_commit.url }}"
              ;;
            esac ;;
          pull_request)
            if [ "${{ github.event.action }}" == opened ]; then
              msg="Pull request ${{ github.event.number }}"
              msg="$msg (\"${{ github.event.pull_request.title }}\")"
              msg="$msg ${{ github.event.action }}"
              url="${{ github.event.pull_request.html_url }}"
            fi ;;
          esac

          echo "EBBR_IRC_MESSAGE=$msg" >> $GITHUB_ENV
          echo "EBBR_IRC_URL=$url" >> $GITHUB_ENV

      - name: 'Notify IRC'
        uses: Gottox/irc-message-action@v2
        if: ${{ github.repository == 'vstehle/ebbr' &&
                env.EBBR_IRC_MESSAGE != '' }}
        with:
          server: irc.oftc.net
          channel: '##vstehle'
          nickname: ebbr-bot
          message: |-
            ${{ env.EBBR_IRC_MESSAGE }}
            ${{ env.EBBR_IRC_URL }}
