---
name: 'EBBR CI Build'

# yamllint disable-line rule:truthy
on:
  push:
    branches: '**'
    tags: 'v*'

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Compute IRC message'
        # We compute a message only in the following cases:
        # - Push to the irc branch
        # - Pull request opened for the main branch
        run: |
          cat >message <<EOF
          ${{ github.event.head_commit.message }}
          EOF

          case "${{ github.event_name }}" in
          push)
            case "${{ github.event.ref }}" in
            refs/heads/irc|refs/tags/*)
              title=$(head -1 message)
              msg="Push ${{ github.event.ref }} (\"$title\")"
              url="${{ github.event.head_commit.url }}"
              ;;
            esac ;;
          pull_request)
            case "${{ github.event.action }}" in
            opened)
              full_name="${{ github.event.pull_request.base.repo.full_name }}"
              ref="${{ github.event.pull_request.base.ref }}"

              if [ "$full_name" == 'vstehle/ebbr' ] && [ "$ref" == main ]; then
                msg="Pull request ${{ github.event.number }}"
                msg="$msg (\"${{ github.event.pull_request.title }}\")"
                msg="$msg ${{ github.event.action }}"
                url="${{ github.event.pull_request.html_url }}"
              fi ;;
            esac ;;
          esac

          echo "EBBR_IRC_MESSAGE=$msg" >> $GITHUB_ENV
          echo "EBBR_IRC_URL=$url" >> $GITHUB_ENV

      - name: 'Notify IRC'
        uses: Gottox/irc-message-action@v2
        # We notify IRC only for the main repository.
        if: ${{ github.repository == 'vstehle/ebbr' &&
                env.EBBR_IRC_MESSAGE != '' }}
        with:
          server: irc.oftc.net
          channel: '##vstehle'
          nickname: ebbr-bot
          message: |-
            ${{ env.EBBR_IRC_MESSAGE }}
            ${{ env.EBBR_IRC_URL }}
